### ISSUE TITLE
Can you go across multiple nodes?

### ISSUE THREAD

**Issue by tonyreina** [tensorflow/mesh#11]
Is it possible to use devices that are on different machines?  For example, in Horovod I can specify the IP addresses of multiple machines and do data parallelism across them. However, this requires me to specifically have MPI setup on each machine. It's unclear to me if this can be done with TF Mesh. Maybe with a tf.train.clusterspec and the parameter server model??

Thanks.
-Tony

**Comment by hpc-unex** [comment]
Did you found a solution for this? @toponado

**Comment by aprabh2** [comment]
Is there a response to this question?
