### ISSUE TITLE
Incorrect tensorflow dependency requirements

### ISSUE THREAD

**Issue by strin** [tensorflow/mesh#32]
In `setup.py`, the tensorflow requirement is `>=1.15`. However, in `mesh_tensorflow.utils`:

```
with tf.summary.create_file_writer(model_dir).as_default():
```

here `tf.summary` is a 2.0 module. so when using gin config

```
utils.tpu_estimator_model_fn.tpu_summaries = True
```

it throws an error with tensorflow 1.15:

![image](https://user-images.githubusercontent.com/2183232/67818002-fbd59000-fa6c-11e9-9fbd-e201dc95ecb0.png)

**Comment by adarob** [comment]
Thanks for raising this issue. It looks like we need to change it to use `tf.compat.v2.summary.create_file_writer`.
