### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'

### ISSUE THREAD

**Issue by Xnhyacinth** [tensorflow/mesh#392]
When I finetune T5 with  [code](https://github.com/google-research/google-research/tree/master/t5_closed_book_qa), I find myself with the following error: `AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'`.

The full stacktrace is the following:
```Traceback (most recent call last):
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/site-packages/t5/models/__init__.py", line 17, in <module>
    import t5.models.mesh_transformer
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/site-packages/t5/models/mesh_transformer.py", line 21, in <module>
    import mesh_tensorflow.transformer.dataset as transformer_dataset
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/site-packages/mesh_tensorflow/__init__.py", line 26, in <module>
    from mesh_tensorflow import simd_mesh_impl
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 27, in <module>
    from mesh_tensorflow import tpu_variables
  File "/data/liaohuanxuan/micromamba/envs/py39/lib/python3.9/site-packages/mesh_tensorflow/tpu_variables.py", line 226, in <module>
    ops.register_tensor_conversion_function(ReplicatedVariable, _tensor_conversion)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'
```

**Comment by RosaliaTufano** [comment]
I'm having the same error while trying to import the learning rete schedule:

`from mesh_tensorflow.transformer.learning_rate_schedules import learning_rate_schedule_noam`

**Comment by jdsannchao** [comment]
> I'm having the same error while trying to import the learning rete schedule:
> 
> `from mesh_tensorflow.transformer.learning_rate_schedules import learning_rate_schedule_noam`

Hi may I ask if you have seen this error before when finetune T5: 

Closing session due to error Graph execution error:

From /job:worker/replica:0/task:0:
Trying to modify element 0 in a list with 0 elements.
	 [[{{node while/body/_1/cond/else/_155/TensorArrayV2Write_2/TensorListSetItem}}]]
	 [[while/IteratorGetNext]]

**Comment by Xnhyacinth** [comment]
> ing_rate_schedule_noam

you can solve it with modifying the `tpu_variables.py` file: 
`from tensorflow.python.framework import tensor_conversion_registry
tensor_conversion_registry.register_tensor_conversion_function(ReplicatedVariable, _tensor_conversion)`
replaces of 
`ops.register_tensor_conversion_function(ReplicatedVariable, _tensor_conversion)`

**Comment by RosaliaTufano** [comment]
> > ing_rate_schedule_noam
> 
> you can solve it with modifying the `tpu_variables.py` file: `from tensorflow.python.framework import tensor_conversion_registry tensor_conversion_registry.register_tensor_conversion_function(ReplicatedVariable, _tensor_conversion)` replaces of `ops.register_tensor_conversion_function(ReplicatedVariable, _tensor_conversion)`

Thank you Xnhyacinth, it seems to work!
